language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    fast_finish: true

before_script:
    - composer self-update
    - composer update

script:
    - cd $TRAVIS_BUILD_DIR
    - vendor/bin/phpunit -c test/phpunit.xml --coverage-clover=./build/clover.xml
    - vendor/bin/phpcs --standard=PSR2 -s -p src/

after_script:
    - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then vendor/bin/ocular code-coverage:upload build/clover.xml --format=php-clover; fi
